language: python

before_install:
- sudo apt-get update -qq
- sudo apt-get install texlive-latex-base texlive-latex-extra latexmk

install:
  - pip install -r requirements.txt

script:
  # Use Sphinx to make the html docs
  - make html
  - make latexpdf LATEXMKOPTS="-silent -f"
  # Tell GitHub not to use jekyll to compile the docs
  - touch _build/html/.nojekyll

# Tell Travis CI to copy the documentation to the gh-pages branch of
# your GitHub repository.
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  local_dir: _build/html/
