language: python

before_install:
  # Update aptitude repository
  - sudo apt-get -qq update

  # Install TexLive 2015 Distribution 
  # This includes the recommended fonts, LaTeX packages, and the XeLaTeX
  # compiler
  - sudo apt-get install -y --no-install-recommends texlive-fonts-recommended \
    texlive-latex-extra \
    texlive-fonts-extra \
    dvipng \
    texlive-latex-recommended \
    texlive-xetex

  # Install decompression tool to extract LaTex packages later on
  - sudo apt-get install -y xzdec

  # Install biber for .bib compilation
  - sudo apt-get install -y biber

  # Initialize user tree for installing additional packages
  - sudo tlmgr init-usertree

  # Define repository for obtaining LaTeX packages (using TexLive 2015)
  - sudo tlmgr option repository ftp://tug.org/historic/systems/texlive/2015/tlnet-final

  # ----------------------------------------------------------------------------
  #   INSTALL ADDITIONAL PACKAGES HERE
  # ----------------------------------------------------------------------------

  - sudo tlmgr install \
    hyperref       \
    parskip        \
    babel          \
    tools          \
    graphics       \
    xcolor
    
install:
  - pip install -r requirements.txt

script:
  # Use Sphinx to make the html docs
  - make html
  - make latexpdf LATEXMKOPTS="-silent -f"
  # Tell GitHub not to use jekyll to compile the docs
  - touch _build/html/.nojekyll

# Tell Travis CI to copy the documentation to the gh-pages branch of
# your GitHub repository.
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  local_dir: _build/html/
