site_name: Sistema Informativo Linee di Attività
repo_name: 'consiglionazionaledellericerche/sigla-main'
repo_url: 'https://github.com/consiglionazionaledellericerche/sigla-main'
# Copyright
copyright: 'Copyright &copy; 2004 - 2020 Consiglio Nazionale delle Ricerche'
extra_css:
  - css/extra.css
nav:
  - Funzionalità di servizio:
      - Coda di Stampa: funzionalita_servizio/coda_di_stampa.md
      - Coda file Excel: funzionalita_servizio/coda_file_excel.md
      - Messaggi: funzionalita_servizio/messaggi.md
      - Gestione Preferiti: funzionalita_servizio/gestione_preferiti.md
  - Configurazione:
      - Progetti di Ricerca:
          - Area Progettuale: configurazione/area_progettuale.md
          - Progetti: configurazione/progetti.md
          - Tabelle di Riferimento: configurazione/tabelle_riferimento.md
      - Gruppo di Azioni Elementari: configurazione/gae.md
      - Piano dei Conti Finanziario: configurazione/piano_conti_finanziario.md
  - Nuovo Layout: nuovo_layout.md
  - Changelog: CHANGELOG.md
theme:
  name: 'material'
  logo: 'logo.png'
  language: 'it'